Handle ir_attachment.location != file FIX TypeError: ord() expected string of length 1, but int found FIX AttributeError: 'res.users' object has no attribute 'password_crypt' FIX as we are not correctly generating metadata, don't require signed responses, since default metadata configurations do not require them FIX RecursionError: maximum recursion depth exceeded